# Generated by Django 3.1.2 on 2020-11-26 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicio',
            new_name='Service',
        ),
    ]
